### PR TITLE
fix: Capitalize the itemName 

### LINKED ISSUE #201: fix:`item-name` only works if capitalised (crud)
This works:

```
<SpCrud store-name="cosmos.blog.blog" item-name="Product" />
```

This doesn't:

```
<SpCrud store-name="cosmos.blog.blog" item-name="product" />
```

### PR DESCRIPTION
**Pull request by mihailmarcu**
## Description & Context

All requests to the blog item use camel case naming conventions and are strictly dependent on them. For now, we allow names that can start with a lowercase letter and break requests. We now convert the `itemName` property to start with uppercase.

## How To Test

1. Open the [Data.view](https://github.com/tendermint/vue/blob/develop/packages/template/src/views/Data.vue) template;
2. For `item-name` prop try using the name like `item-name="modelName"` or `item-name="ModelName"`;
3. In both cases the module should work;

## Linked issue

Closes #201

### CODE REVIEW

File: packages/vue/src/components/SpCrud/SpCrud.vue [hunk 1]
```diff
@@ -117,11 +118,15 @@ export default defineComponent({
 
     // state
     let state: State = reactive(initialState)
+    let moduleName = computed (() =>
```
Comment (marinhoarthur) [inline packages/vue/src/components/SpCrud/SpCrud.vue]: Let's either use `item` or `module` for naming this. 

For the case insensitive version, let's use something like `<name>Normalized `

Comment (marinhoarthur) [reply packages/vue/src/components/SpCrud/SpCrud.vue]: also mind placing the computed in a separate code block following ` // computed` comment

**Review by marinhoarthur — CHANGES_REQUESTED** [review]

File: packages/vue/src/components/SpCrud/SpCrud.vue [hunk 2]
```diff
@@ -117,11 +118,15 @@ export default defineComponent({
 
     // state
     let state: State = reactive(initialState)
```
Comment (marinhoarthur) [inline packages/vue/src/components/SpCrud/SpCrud.vue:117]: Let's use this PR to switch `moduleAvailable`'s  initial value back to `false`

**Review by marinhoarthur — APPROVED** [review]
